### ISSUE TITLE
ART finding significant effects that do not seem to exist

### ISSUE THREAD

**Issue by casiez** [mjskay/ARTool#36]
An ANOVA on an ART finds a significant effect of X2 on Y in the following dataset: [data.csv](https://github.com/mjskay/ARTool/files/9513347/data.csv)

```r
library(dplyr)
library(ARTool) # version 0.11.1
library(lme4)
library(plotly)
library(bootES)

df = read.csv("https://github.com/mjskay/ARTool/files/9513347/data.csv", sep=";")
# assume 'S' is the name of the subjects column
# assume 'X1' is the name of the first factor column (3 levels: H, L and M)
# assume 'X2' is the name of the second factor column (2 levels: P and T)
# assume 'X3' is the name of the third factor column (3 levels: 1, 2 and 3)
# 'X1' , 'X2' and 'X3'  are within-subjects variables
# assume 'Y' is the name of the response column

# run the ART procedure on 'df'
df$X1 = factor(df$X1)
df$X2 = factor(df$X2)
df$X3 = factor(df$X3)

m = art(Y ~ X1 * X2 * X3 + (1|S), data=df) # linear mixed model syntax; see lme4::lmer
summary(m)
```
This outputs:
```
Aligned Rank Transform of Factorial Model

Call:
art(formula = Y ~ X1 * X2 * X3 + (1 | S), data = df)

Column sums of aligned responses (should all be ~0):
      X1       X2       X3    X1:X2    X1:X3    X2:X3 X1:X2:X3 
       0        0        0        0        0        0        0 

F values of ANOVAs on aligned responses not of interest (should all be ~0):
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      0       0       0       0       0       0 
```
Which suggests everything is right to run the ANOVA.

```r
anova(m)
```
Here is the output:
```
## Analysis of Variance of Aligned Rank Transformed Data
## 
## Table Type: Analysis of Deviance Table (Type III Wald F tests with Kenward-Roger df) 
## Model: Mixed Effects (lmer)
## Response: art(Y)
## 
##                     F Df Df.res     Pr(>F)    
## 1 X1       1326.60837  2    289 < 2.22e-16 ***
## 2 X2          7.65014  1    289  0.0060424  **
## 3 X3         21.37221  2    289 2.2061e-09 ***
## 4 X1:X2       1.22885  2    289  0.2941532    
## 5 X1:X3       4.48146  4    289  0.0015789  **
## 6 X2:X3       1.50265  2    289  0.2242741    
## 7 X1:X2:X3    0.31126  4    289  0.8703617    
## ---
## Signif. codes:   0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```
There is a significant main effect of X2 (F(2,289)=7.6, p=0.006).

We now create a figure representing the mean values for the 2 levels of X2 (P and T) and their 95% CI:

```r
Y_X2_P = df %>% filter(X2 == "P")
Y_X2_P_mean = mean(Y_X2_P$Y)
Y_X2_P_CI_lower = bootES(Y_X2_P$Y)$bounds[1]
Y_X2_P_CI_upper = bootES(Y_X2_P$Y)$bounds[2]

Y_X2_T = df %>% filter(X2 == "T")
Y_X2_T_mean = mean(Y_X2_T$Y)
Y_X2_T_CI_lower = bootES(Y_X2_T$Y)$bounds[1]
Y_X2_T_CI_upper = bootES(Y_X2_T$Y)$bounds[2]

fig <- plot_ly(
  x = c("P", "T"),
  y = c(Y_X2_P_mean, Y_X2_T_mean),
  error_y = list(symmetric=F, array=c(Y_X2_P_CI_upper - Y_X2_P_mean, Y_X2_T_CI_upper - Y_X2_T_mean),
  arrayminus=c(Y_X2_P_mean - Y_X2_T_CI_lower, Y_X2_T_mean - Y_X2_T_CI_lower), color = '#000000'),
  type = "bar"
)

fig
```
The result is the following:
![figure](https://user-images.githubusercontent.com/3748153/188980628-23e3abf9-55e0-4be9-a624-68fed33bad31.png)

According to this figure and the overlapping of the 95% CI, it seems very unlikely the significant effect exists.

Also a Wilcoxon test does not find a significant effect:
```r
dataAggr = df %>% group_by(S, X2) %>%
    summarize(Y = mean(Y))
P = dataAggr %>% filter(X2 == "P")
T = dataAggr %>% filter(X2 == "T")
wilcox.test(P$Y, T$Y, paired=TRUE)
```
Output:
```
	Wilcoxon signed rank test with continuity correction

data:  P$Y and T$Y
V = 117, p-value = 0.1769
alternative hypothesis: true location shift is not equal to 0
```

Is there something wrong in the code above? Is it a problem with the dataset or a problem with the ART itself?

**Comment by mattrussell2** [comment]
Interesting question! I'm no expert, but here's my two cents. 

I agree that the plot you've presented here does seem to indicate that there isn't much of an effect here visually...however, it *might* be that the repeated measures nature of the data is getting in the way, and collapsing to the mean of each participant might not be able to capture some nuance of the dataset. To check this out, I tried `lmer` without ART:

```
library(lmerTest)
lmer_mdl <- lmerTest::lmer(Y ~ X1 * X2 * X3 + (1 | S), data=df)
anova(lmer_mdl)
```
```
Type III Analysis of Variance Table with Satterthwaite's method
         Sum Sq Mean Sq NumDF DenDF  F value  Pr(>F)    
X1       999597  499798     2   289 373.0689 < 2e-16 ***
X2         1361    1361     1   289   1.0157 0.31437    
X3         8625    4313     2   289   3.2191 0.04143 *  
X1:X2       492     246     2   289   0.1837 0.83229    
X1:X3      4008    1002     4   289   0.7479 0.56006    
X2:X3       494     247     2   289   0.1842 0.83183    
X1:X2:X3    642     160     4   289   0.1197 0.97541    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```
But checking the residuals of the model shows 
```
hist(resid(lmer_mdl))
```
<img width="663" alt="image" src="https://github.com/mjskay/ARTool/assets/26848038/be0fc08c-4c19-46c9-ba2e-d1b06cde2ac4">

Clearly these are not normally distributed. Taking a closer look at the distribution of the response variable:
```
hist(df$Y)
```
<img width="665" alt="image" src="https://github.com/mjskay/ARTool/assets/26848038/13df8aa6-3294-418c-b389-78d8d574ca3d">

Aha, perhaps a log transform might help? We can check also check the distribution of the data with:

```
library(fitdistrplus)
descdist(df$Y, discrete=FALSE)
```
<img width="665" alt="image" src="https://github.com/mjskay/ARTool/assets/26848038/e66aa4a2-7651-414c-8e0d-973ec0a10845">

Indeed, lognormal seems appropriate enough. So what happens when we apply a log transform?

```
df$Y <- log(df$Y)
lmer_log_m = lmerTest::lmer(Y ~ X1 * X2 * X3 + (1 | S), data=df)
anova(lmer_log_m)
```
```
Type III Analysis of Variance Table with Satterthwaite's method
         Sum Sq Mean Sq NumDF DenDF   F value    Pr(>F)    
X1       93.413  46.706     2   289 1508.1869 < 2.2e-16 ***
X2        0.191   0.191     1   289    6.1682   0.01357 *  
X3        0.749   0.374     2   289   12.0868 9.094e-06 ***
X1:X2     0.012   0.006     2   289    0.2007   0.81830    
X1:X3     0.112   0.028     4   289    0.9079   0.45967    
X2:X3     0.025   0.012     2   289    0.4012   0.66989    
X1:X2:X3  0.010   0.002     4   289    0.0783   0.98889    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

And the residuals of the model?
```
hist(resid(lmer_log_m))
```
<img width="665" alt="image" src="https://github.com/mjskay/ARTool/assets/26848038/6e109adc-0cbe-40c4-aa51-96a123218f55">

The Wilcoxon test on the transformed data is still not significant, however it's much closer; taking your code from earlier 
```
dataAggr <- df %>% group_by(S, X2) %>%
    summarize(Y = mean(Y))
P = dataAggr %>% filter(X2 == "P")
T = dataAggr %>% filter(X2 == "T")
wilcox.test(P$Y, T$Y, paired=TRUE)
```
```
wilcox.test(P$Y, T$Y, paired=TRUE)
`summarise()` has grouped output by 'S'. You can override using
the `.groups` argument.

        Wilcoxon signed rank exact test

data:  P$Y and T$Y
V = 129, p-value = 0.05994
alternative hypothesis: true location shift is not equal to 0
```

So the world is all better, yes? It's just a nuance with the non-normal nature of the data and the repeated measures?

Well....

Running `check_model` on the lmer model shows that, among other things, there is a high degree of collinearity. 

```
library(performance)
check_model(m)
```
<img width="666" alt="image" src="https://github.com/mjskay/ARTool/assets/26848038/93e1ca86-3941-4dc9-872c-64cedb8a23b8">


Depending on the aim of your model, this may certainly be problematic. And indeed, when attempting to find (in the original dataset), the post-hoc contrast for X2, we find 

```
m = art(Y ~ X1 * X2 * X3 + (1 | S), data=df)
art.con(m, "X2", adjust="holm")
```
```
NOTE: Results may be misleading due to involvement in interactions
 contrast estimate   SE  df t.ratio p.value
 P - T        18.6 6.71 289   2.766  0.0060
```
*NOTE: Results may be misleading due to involvement in interactions* doesn't seem like something to ignore! 

Going back to the `lmer` model with the log-transformed Y, how about a LRT between a null model, a model with only X1 and X3, and the original model?
```
m0 = lmerTest::lmer(Y ~(1 | S), data=df)
m1 = lmerTest::lmer(Y ~ X1 * X3 + (1 | S), data=df)
m2 = lmerTest::lmer(Y ~ X1 * X2 * X3 + (1 | S), data=df)
anova(m0, m1, m2)
```
```
refitting model(s) with ML (instead of REML)
Data: df
Models:
m0: Y ~ (1 | S)
m1: Y ~ X1 * X3 + (1 | S)
m2: Y ~ X1 * X2 * X3 + (1 | S)
   npar     AIC    BIC   logLik deviance    Chisq Df Pr(>Chisq)    
m0    3  593.54 604.89 -293.771   587.54                           
m1   11 -131.38 -89.79   76.690  -153.38 740.9220  8     <2e-16 ***
m2   20 -121.41 -45.80   80.705  -161.41   8.0308  9      0.531    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```
Interesting - the AIC/BIC are lower for m1 than m2, and the Chisq test is not significant. 

My takeaway is that, while the statistical significance of X2 is legit (given repeated measures), ultimately the factor is redundant and should likely be removed from the model. That said, I'm really not sure if the details of the ART process would change things from the analysis of the lmer models presented here.

**Comment by mjskay** [comment]
Thanks for the detailed diagnostics @mattrussell2. I took a look as well and I agree this looks like a case where repeated measures makes a difference. 

In general, you can't judge the significance of a difference between two variables by comparing marginal intervals on them, because if there is correlation between the variables (as in the case of repeated measures), the visual heuristics you might use for comparing two independent variables will not work. Think of the case where the value at both levels of a factor has high variance, but every subjects decreases a consistent --- but small --- amount: looking at the population level means and intervals there may be a lot of overlap, but an estimate of the average individual-level difference could be precise and non-zero. The question then is: apart from statistical significance, is the difference practically meaningful? You can't really answer that without domain knowledge, which should be used to judge if any statistically significant effect is practically meaningful.

With respect to the paired Wilcoxon, you summarized to just compare the means of each subject within each group (a necessary step, because the Wilcoxon only allows one observation per group). Likely this lost you some statistical power that the mixed models have because they can allow for multiple observations per person per group. That would explain the discrepancy.

**Comment by ephanis** [comment]
This very interesting issue motived us (with @casiez) to conduct a series of experiments during the last year to re-evaluate ART. We just [submitted our results](https://github.com/journalovi/jovi-submissions/issues/3) to the experimental track of JoVI.

Our findings are in line with past results by Lüpsen (2017, 2018). Overall, **we conclude that ART is defective and should not be used**. Surprisingly, ART only works correctly when distributions are normal, variances are equal, and there are no missing data.

Concerning the above example, it’s true that using Wilcoxon on aggregated data is not the best approach for reasons explained in the previous comment by @mjkay. Here, I would tend to give more trust on the log-transformation (LOG), as proposed by @mattrussell2. Indeed, LOG also provides evidence for an effect of X2 (_p = .01357_). 

Still, we can notice some other discrepancies between the results of LOG and ART:

- ART detects an interaction effect  X1:X3 (_p = .00157_), while LOG does not (_p = .45697_). 
- ART’s _p_-value for the effect X3 (_e-09_) is three orders of magnitude lower than the p-value of LOG (_e-06_). If we further estimate effect sizes, we find _eta-squared = .13 [.07, 1.00]_ with ART, and _eta-squared = .08 [.03, 1.00]_ with LOG. 

We can also conduct an analysis with the Inverse Normal Transformation (INT). We also discuss and evaluate this simple rank-based method in our JoVI submission. We find it as the most versatile and most robust non-parametric procedure, although we also raise some flags. For a quick justification of this very simple method, see [Gelman’s blog](https://statmodeling.stat.columbia.edu/2015/07/13/dont-do-the-wilcoxon/).

```
# Implementation of the Inverse Normal Transform
int = function(x){
   qnorm((rank(x) - 0.5)/length(x))
}

mint <- lmer(int(Y) ~ X1*X2*X3 + (1|S), data=df)
```

Results:
```
Type III Analysis of Variance Table with Satterthwaite's method
           Sum Sq Mean Sq NumDF DenDF  F value    Pr(>F)    
X1       229.306 114.653     2   289 994.3261 < 2.2e-16 ***
X2         0.757   0.757     1   289   6.5610   0.01093 *  
X3         3.287   1.644     2   289  14.2538 1.248e-06 ***
X1:X2      0.002   0.001     2   289   0.0066   0.99338    
X1:X3      0.732   0.183     4   289   1.5868   0.17782    
X2:X3      0.110   0.055     2   289   0.4772   0.62099    
X1:X2:X3   0.078   0.020     4   289   0.1697   0.95372    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```
Overall, results of INT are consistent with results of LOG, showing no evidence for an interaction effect. I don’t present the details here, but INT’s effect size estimate for X3 is _eta-squared = 09 [.04, 1.00]_. 

Our paper presents better examples of how ART fails. For instance, see [this example](https://statransform.github.io/jovi/supplementary/examples-case-studies/1-Introduction/illustrative-example.html), where data are drawn from lognormal distributions. Or [this real case study](https://statransform.github.io/jovi/supplementary/examples-case-studies/6-Case-studies/Rosso-et-al-23/Rosso-et-al-23.html), where data are ordinal. 

In the paper, we show that such discrepancies are very systematic. ART confounds effects: a strong effect on one factor makes it detect non-existent effects (or exaggerate effect sizes) on other factors. 

In addition, it completely fails in certain types of discrete data, such as binary data, binomial distributions, Likert-type data with 5 or 7 levels, especially when thresholds are flexible (i.e., ordinal scales where levels are not equidistant). Note that ART has been very little evaluated in the past for such types of distributions, and despite this fact, it is commonly used in particular for these types of data.

Our results will go through an official review process, so we understand that our recommendations cannot be taken for granted. However, we encourage the developers of the ARTool to take into account these results, conduct their own investigations, and raise quick warnings if needed, because we observe that ART is increasingly used in some communities. This is despite the previous warnings of Lüpsen (2017, 2018).
