### ISSUE TITLE
Write a vignette for contrasts of levels in one factor conditional on some level of another factor

### ISSUE THREAD

**Issue by mjskay** [mjskay/ARTool#8]
E.g. A vs B within C (from the existing interactions vignette)

**Comment by verfolvarska** [comment]
My analysis involves two factors: Condition (6 levels) and ARB Type (7 levels). I’m trying to extract contrasts of the conditions within each individual ARB Type, rather than across all combinations. This seems similar to an earlier issue that was marked as resolved, but I’m still struggling to locate where in the documentation this specific use case is addressed.

I understand that ART-C can be used to generate all possible comparisons, but that results in 1128 contrasts—many of which aren’t biologically meaningful for my application. Is there a way to get comparisons for levels in a factor grouped by levels in another factor?
